#!/usr/bin/env node
// S2 portable, bounded offline commands. No network and no implicit source overwrites.
import { readFile, writeFile, link, rm, stat } from 'node:fs/promises';
import { resolve, dirname, extname } from 'node:path';
import { randomBytes } from 'node:crypto';
import { inspectSvg, constructLogo } from './topology.mjs';
import { analyze } from '../s1/geometry.mjs';
const details={version:'geometric-design-s2/1',modes:['logo-standard','logo-multi-part'],supported:['axis-aligned rect/rectangular path or polygon groups','analytic circles with contained white counters','singleton ellipse'],unsupported:['mixed or intersecting curved booleans','arbitrary Q/C/A path commands','stroke/clip/filter/style/text','S3 raster recognition'],network:false};
const err=(code,path,msg)=>{const e=new Error(msg);e.code=code;e.path=path;throw e};
function args(argv){const [command,input,...rest]=argv;let flags={};for(let i=0;i<rest.length;i+=2){if(!rest[i]?.startsWith('--')||rest[i+1]===undefined)err('INPUT_ERROR','args','Expected --name value pairs');const k=rest[i].slice(2);if(!['out','report','mode'].includes(k)||Object.hasOwn(flags,k))err('INPUT_ERROR','args','Unknown/repeated flag');flags[k]=rest[i+1]}return {command,input,flags}}
async function atomicOut(file,text){let path=resolve(file),tmp=path+'.tmp-'+randomBytes(8).toString('hex');try{await stat(path);err('OUTPUT_EXISTS',path,'Refuse overwrite existing file')}catch(e){if(e.code!=='ENOENT')throw e}try{await writeFile(tmp,text,{flag:'wx'});await link(tmp,path);await rm(tmp)}catch(e){await rm(tmp,{force:true}).catch(()=>{});throw e}}
export async function runCLI(argv){const {command,input,flags}=args(argv);if(command==='capabilities'&&!input)return {code:0,output:details};if(!['validate','construct'].includes(command)||!input)err('INPUT_ERROR','command','Use validate FILE or construct FILE');const inputPath=resolve(input);const text=await readFile(inputPath,'utf8');if(text.length>100000)err('LIMIT_EXCEEDED','input','Source size limit');let result,svgOut=null;if(command==='validate'){if(flags.out)err('INPUT_ERROR','--out','validate accepts --report only');
if(extname(inputPath)==='.svg')result=inspectSvg(text,{mode:flags.mode??'logo-standard'});
else if(extname(inputPath)==='.json'){const d=JSON.parse(text),a=analyze(d),top=constructLogo(d);result={schema:'geometry-validate-report/1',sourceDigest:a.sourceDigest,constraints:a.constraints,topology:top.topology??null,status:top.status}}
else err('INPUT_ERROR','input','Requires .svg or .json');
}else{if(extname(inputPath)!=='.json')err('INPUT_ERROR','input','Construct requires geometry-document JSON');const d=JSON.parse(text);const r=constructLogo(d);result={schema:'geometry-construct-report/1',status:r.status,sourceDigest:r.sourceDigest,constraints:r.constraints,topology:r.topology??null};svgOut=r.svg;if(!flags.out)err('INPUT_ERROR','--out','Explicit --out SVG path required')}
for(const path of [flags.out,flags.report])if(path&&resolve(path)===inputPath)err('INPUT_ERROR','output','Refuse to overwrite source');if(flags.out&&flags.report&&resolve(flags.out)===resolve(flags.report))err('INPUT_ERROR','output','Out/report path collision');if(svgOut&&flags.out)await atomicOut(flags.out,svgOut);if(flags.report)await atomicOut(flags.report,JSON.stringify(result,null,2)+'\n');return {code:result.status==='PASS'?0:3,output:result}}
if(process.argv[1]&&resolve(process.argv[1])===resolve(new URL(import.meta.url).pathname)){runCLI(process.argv.slice(2)).then(r=>{console.log(JSON.stringify(r.output));process.exitCode=r.code}).catch(e=>{console.error(JSON.stringify({error:e.code??'INTERNAL_ERROR',message:e.message,path:e.path}));process.exitCode=e.code==='UNSUPPORTED_GEOMETRY'||e.code==='UNSUPPORTED_SVG'?4:e.code==='INVALID_SVG'||e.code==='INVALID_POLICY'||e.code==='INVALID_NUMBER'||e.code==='INPUT_ERROR'||e.code==='OUTPUT_EXISTS'||e.code==='INVALID_SCHEMA'?2:5})}
