// Portable S2: exact arrangement of axis-aligned rectangular fill regions, analytic disks.
// Explicitly reject geometry outside proven capabilities instead of claiming a false pass.
import { parseSvg, constructSvg, svgError } from './svg.mjs';
import { analyze } from '../s1/geometry.mjs';
const EPS=1e-10;
const overlaps=(a,b)=>Math.min(a.x1,b.x1)-Math.max(a.x0,b.x0)>EPS&&Math.min(a.y1,b.y1)-Math.max(a.y0,b.y0)>EPS;
const inRect=(x,y,r)=>x>r.x0&&x<r.x1&&y>r.y0&&y<r.y1;
const sortUnique=a=>[...new Set(a)].sort((x,y)=>x-y);
const status=(components,holes,mode,detail)=>({schema:'geometry-topology/1',status:components===0||mode==='logo-standard'&&components!==1?'FAIL':'PASS',components,holes,mode,...detail});
function rectangleTopology(canvas,items,mode){const [x,y,w,h]=canvas.viewBox,xb=sortUnique([x,x+w,...items.flatMap(t=>t.contours.flatMap(r=>[r.x0,r.x1])).filter(v=>v>x&&v<x+w)]),yb=sortUnique([y,y+h,...items.flatMap(t=>t.contours.flatMap(r=>[r.y0,r.y1])).filter(v=>v>y&&v<y+h)]);const width=xb.length-1,height=yb.length-1;if(width*height>1000000)svgError('LIMIT_EXCEEDED','topology','Rectilinear arrangement exceeds one million cells');const filled=new Uint8Array(width*height);const ix=(i,j)=>j*width+i;for(let j=0;j<height;j++)for(let i=0;i<width;i++){const cx=(xb[i]+xb[i+1])/2,cy=(yb[j]+yb[j+1])/2;let black=false;for(const item of items){const containing=item.contours.filter(r=>inRect(cx,cy,r));const inside=item.fillRule==='evenodd'?containing.length%2===1:containing.reduce((n,r)=>n+r.winding,0)!==0;if(inside)black=item.fill==='#000000'}filled[ix(i,j)]=Number(black)}
const seen=new Uint8Array(filled.length);const groups=[];const moves=[[1,0],[-1,0],[0,1],[0,-1]];let minBlackCellWidth=Infinity,minBlackCellHeight=Infinity,blackArea=0;for(let j=0;j<height;j++)for(let i=0;i<width;i++){if(!filled[ix(i,j)])continue;minBlackCellWidth=Math.min(minBlackCellWidth,xb[i+1]-xb[i]);minBlackCellHeight=Math.min(minBlackCellHeight,yb[j+1]-yb[j]);blackArea+=(xb[i+1]-xb[i])*(yb[j+1]-yb[j]);if(seen[ix(i,j)])continue;let stack=[[i,j]],cells=0;seen[ix(i,j)]=1;while(stack.length){const [a,b]=stack.pop();cells++;for(const [dx,dy]of moves){let u=a+dx,v=b+dy;if(u<0||u>=width||v<0||v>=height||!filled[ix(u,v)]||seen[ix(u,v)])continue;seen[ix(u,v)]=1;stack.push([u,v])}}groups.push({cells})}
let holes=0;const visited=new Uint8Array(filled.length);for(let j=0;j<height;j++)for(let i=0;i<width;i++){if(filled[ix(i,j)]||visited[ix(i,j)])continue;let touchesBoundary=false,q=[[i,j]];visited[ix(i,j)]=1;while(q.length){const [a,b]=q.pop();if(a===0||a===width-1||b===0||b===height-1)touchesBoundary=true;for(const [dx,dy]of moves){const u=a+dx,v=b+dy;if(u<0||u>=width||v<0||v>=height||filled[ix(u,v)]||visited[ix(u,v)])continue;visited[ix(u,v)]=1;q.push([u,v])}}if(!touchesBoundary)holes++}
// Count zero-width or point-only candidate contacts in a diagnostic, never connectivity.
let pointContacts=0;const rects=items.flatMap(it=>it.fill==='#000000'&&it.contours.length===1?it.contours:[]);for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++){const a=rects[i],b=rects[j],dx=Math.min(a.x1,b.x1)-Math.max(a.x0,b.x0),dy=Math.min(a.y1,b.y1)-Math.max(a.y0,b.y0);if(dx<=EPS&&dx>=-EPS&&dy<=EPS&&dy>=-EPS)pointContacts++}
let exactRectCounterMargin=null,exactDisjointRectSeparation=null;
const singleBlack=items.filter(t=>t.fill==='#000000'&&t.contours.length===1),singleWhite=items.filter(t=>t.fill==='#ffffff'&&t.contours.length===1);
if(singleBlack.length===1&&singleWhite.length===1&&items.length===2){const outer=singleBlack[0].contours[0],inner=singleWhite[0].contours[0];if(inner.x0>outer.x0&&inner.x1<outer.x1&&inner.y0>outer.y0&&inner.y1<outer.y1)exactRectCounterMargin=Math.min(inner.x0-outer.x0,outer.x1-inner.x1,inner.y0-outer.y0,outer.y1-inner.y1)}
if(singleBlack.length>=2&&singleBlack.length===items.length){let min=Infinity;for(let i=0;i<singleBlack.length;i++)for(let j=i+1;j<singleBlack.length;j++){const a=singleBlack[i].contours[0],b=singleBlack[j].contours[0],dx=Math.max(0,a.x0-b.x1,b.x0-a.x1),dy=Math.max(0,a.y0-b.y1,b.y0-a.y1);if(dx>0||dy>0)min=Math.min(min,Math.hypot(dx,dy))}if(Number.isFinite(min))exactDisjointRectSeparation=min}
return status(groups.length,holes,mode,{method:'exact-rectilinear-arrangement',area:blackArea,pointContacts,arrangementCells:filled.length,measurements:{exactRectCounterMargin,exactDisjointRectSeparation,minimumPartitionCellWidth:Number.isFinite(minBlackCellWidth)?minBlackCellWidth:null,minimumPartitionCellHeight:Number.isFinite(minBlackCellHeight)?minBlackCellHeight:null,minimumTrueLigamentWidth:'NOT_EVALUATED',minimumTrueWhiteChannelWidth:'NOT_EVALUATED'},raster:'NOT_EVALUATED',recognition:'NOT_EVALUATED'})}
function circleTopology(items,mode,canvas){const [vx,vy,vw,vh]=canvas.viewBox;for(const c of items)if(c.cx-c.r<vx-EPS||c.cy-c.r<vy-EPS||c.cx+c.r>vx+vw+EPS||c.cy+c.r>vy+vh+EPS)svgError('UNSUPPORTED_GEOMETRY',c.id,'Circle clipped by viewport; analytic count unavailable');const blacks=items.filter(x=>x.fill==='#000000'),whites=items.filter(x=>x.fill==='#ffffff');if(!blacks.length)return status(0,0,mode,{method:'analytic-circles',raster:'NOT_EVALUATED',recognition:'NOT_EVALUATED'});
let count=blacks.length,root=blacks.map((_,i)=>i),contacts=0;const find=a=>root[a]===a?a:(root[a]=find(root[a]));const union=(a,b)=>{a=find(a);b=find(b);if(a!==b){root[b]=a;count--}};const d=(a,b)=>Math.hypot(a.cx-b.cx,a.cy-b.cy);
for(let i=0;i<blacks.length;i++)for(let j=i+1;j<blacks.length;j++){const a=blacks[i],b=blacks[j],gap=d(a,b)-a.r-b.r;if(gap<-EPS)union(i,j);else if(Math.abs(gap)<=EPS)contacts++}
// A hole may erase the only bridge between partially overlapping black disks.
// Until a curved arrangement solver exists, refuse this case rather than claiming false connectivity.
if(whites.length)for(let i=0;i<blacks.length;i++)for(let j=i+1;j<blacks.length;j++){
  const a=blacks[i],b=blacks[j],dist=d(a,b);
  if(dist<a.r+b.r-EPS&&dist+Math.min(a.r,b.r)>Math.max(a.r,b.r)+EPS)
    svgError('UNSUPPORTED_GEOMETRY','topology','White erasure in partially overlapping circle union requires curved boolean');
}
// Only strictly contained, mutually disjoint WHITE circles; white erosion crossing a black edge is unsupported.
for(const w of whites){let parent=false;for(const b of blacks){const dist=d(w,b);if(dist+w.r<=b.r-EPS)parent=true;else if(dist+b.r<=w.r+EPS)svgError('UNSUPPORTED_GEOMETRY',w.id,'White erases entire black disk');else if(dist<b.r+w.r+EPS)svgError('UNSUPPORTED_GEOMETRY',w.id,'Partially intersecting/tangent white circle needs curved boolean solver')}if(!parent)svgError('UNSUPPORTED_GEOMETRY',w.id,'White circle not strictly contained in black foreground')}
for(let i=0;i<whites.length;i++)for(let j=i+1;j<whites.length;j++)if(d(whites[i],whites[j])<=whites[i].r+whites[j].r+EPS)svgError('UNSUPPORTED_GEOMETRY',whites[i].id,'Overlapping/touching white erasures unsupported');
if(whites.length&&items.findIndex(x=>x.fill==='#ffffff')<items.findLastIndex(x=>x.fill==='#000000'))svgError('UNSUPPORTED_GEOMETRY','svg','Black redraw after white erasure not modeled');
return status(count,whites.length,mode,{method:'analytic-circles-and-contained-erasures',pointContacts:contacts,measurements:{minWhiteCutoutMargin:whites.length?Math.min(...whites.flatMap(w=>blacks.filter(b=>d(w,b)+w.r<b.r).map(b=>b.r-w.r-d(w,b)))):null,minimumTrueLigamentWidth:'NOT_EVALUATED'},raster:'NOT_EVALUATED',recognition:'NOT_EVALUATED'})}
export function inspectSvg(svg,{mode='logo-standard'}={}){if(!['logo-standard','logo-multi-part'].includes(mode))svgError('INVALID_POLICY','mode','Explicit logo mode required');const parsed=parseSvg(svg),items=parsed.items;const allRects=items.every(x=>x.kind==='rectContours'),allCircles=items.every(x=>x.kind==='circle');if(!items.length)return {...status(0,0,mode,{method:'empty'}),parsed};let result;if(allRects)result=rectangleTopology(parsed.canvas,items,mode);else if(allCircles)result=circleTopology(items,mode,parsed.canvas);else if(items.length===1&&items[0].kind==='ellipse'&&items[0].fill==='#000000')result=status(1,0,mode,{method:'single-ellipse',raster:'NOT_EVALUATED',recognition:'NOT_EVALUATED'});else svgError('UNSUPPORTED_GEOMETRY','topology','S2 supports only rectilinear arrangements, circle-only groups, or single ellipse; mixed shape booleans not claimed');return {...result,sourceType:'svg',canvas:parsed.canvas,shapeCount:items.length}}
export function constructLogo(input){const constraints=analyze(input);if(constraints.constraints.status!=='PASS')return {status:'FAIL',code:'INFEASIBLE',constraints:constraints.constraints,svg:null};const svg=constructSvg(input),mode=input.policy?.mode??'logo-standard';const topology=inspectSvg(svg,{mode});return {status:topology.status,sourceDigest:constraints.sourceDigest,constraints:constraints.constraints,topology,svg:topology.status==='PASS'?svg:null}}
