// S3: measured optical proxy and reversible explicitly proposed edits, never auto-approved.
import {sha256, renderSizes, portableResult} from './raster.mjs';
import {inspectSvg} from '../s2/topology.mjs';
import {parseSvg} from '../s2/svg.mjs';
const fail=(code,message)=>{let e=new Error(message);e.code=code;throw e};
const attr=(element,name)=>{const m=new RegExp('(?:^|\\s)'+name+'="([^\"]*)"').exec(element);return m?.[1]??null};
export function proposeVoidCircleShift(originalSvg,{id,dx,dy,ruleId,reason}={}){
 if(!id||!/^[A-Za-z][\w.-]{0,99}$/.test(id)||!ruleId||!reason?.trim()||reason.length>400)fail('INVALID_PROPOSAL','Stable circle id, rule id and human-readable reason required');
 for(const [label,value] of [['dx',dx],['dy',dy]])if(typeof value!=='number'||!Number.isFinite(value)||Math.abs(value)>1000)fail('INVALID_PROPOSAL',label+' must be finite within +/-1000');
 if(Math.abs(dx)+Math.abs(dy)===0)fail('INVALID_PROPOSAL','Zero optical change');
 const parsed=parseSvg(originalSvg),targets=parsed.items.filter(x=>x.id===id);if(targets.length!==1||targets[0].kind!=='circle'||targets[0].fill!=='#ffffff')fail('UNSUPPORTED_GEOMETRY','Only uniquely named white circle counter can shift in S3');
 const before=inspectSvg(originalSvg);if(before.status!=='PASS')fail('INVALID_SOURCE','Original master fails standard symbol policy');
 let seen=0;const candidate=originalSvg.replace(/<circle\b[^<>]*\/>/g,tag=>{if(attr(tag,'id')!==id)return tag;seen++;if(attr(tag,'transform')!==null)fail('UNSUPPORTED_GEOMETRY','Shift for transformed circle not supported');const x=Number(attr(tag,'cx')??0),y=Number(attr(tag,'cy')??0);if(!Number.isFinite(x)||!Number.isFinite(y))fail('INVALID_SOURCE','Invalid circle position');const f=v=>Number(v.toPrecision(14)).toString();let next=tag;
  if(attr(next,'cx')!==null)next=next.replace(/\bcx="[^"]*"/,'cx="'+f(x+dx)+'"');else next=next.replace(/\s*\/>/,' cx="'+f(x+dx)+'"/>');
  if(attr(next,'cy')!==null)next=next.replace(/\bcy="[^"]*"/,'cy="'+f(y+dy)+'"');else next=next.replace(/\s*\/>/,' cy="'+f(y+dy)+'"/>');return next});
 if(seen!==1)fail('UNSUPPORTED_GEOMETRY','Could not identify exact circle tag');const after=inspectSvg(candidate);if(after.status!=='PASS'||after.components!==before.components||after.holes!==before.holes)fail('TOPOLOGY_REGRESSION','Optical candidate would alter connectedness/counters');
 return {sourceSvg:originalSvg,candidateSvg:candidate,record:{schema:'geometry-optical-exception/1',ruleId,affectedShapeId:id,reason,approval:{status:'PENDING_OWNER_REVIEW',verified:false},status:'PROPOSED_UNAPPROVED',change:{kind:'circle-center-translation',dx,dy,units:'svg-viewBox-unit'},originalSha256:sha256(Buffer.from(originalSvg)),candidateSha256:sha256(Buffer.from(candidate)),originalTopology:{components:before.components,holes:before.holes},candidateTopology:{components:after.components,holes:after.holes},visualQuality:'NOT_EVALUATED',mathematicalMasterPreserved:true}}}
export function compareOpticalProxy(originalSvg,candidateSvg,{size=128}={}){const before=renderSizes(originalSvg,{sizes:[size]}),after=renderSizes(candidateSvg,{sizes:[size]});if(before.status!=='EXECUTED'||after.status!=='EXECUTED')return {status:'BLOCKED_ENV',originalRenderer:before.status,candidateRenderer:after.status};const b=before.results[0].metrics,a=after.results[0].metrics;return {status:'MEASURED_PROXY_ONLY',size,sourceSha256:before.sourceSha256,candidateSha256:after.sourceSha256,centroidBefore:b.visualMassProxyCentroid,centroidAfter:a.visualMassProxyCentroid,frameCenter:[size/2,size/2],offsetBefore:b.visualMassProxyCentroid?.map(x=>x-size/2)??null,offsetAfter:a.visualMassProxyCentroid?.map(x=>x-size/2)??null,renderedBefore:portableResult(before).results[0].pngSha256,renderedAfter:portableResult(after).results[0].pngSha256,visualPreference:'NOT_EVALUATED',recognition:'NOT_EVALUATED',ownerApproval:'NOT_GIVEN'} }
