// S4: standalone read-only geometry auditor. No dependency on Universal Gauntlet.
import { createHash } from 'node:crypto';
import { analyze, PHI, renderedCircleClass, transformPoint } from '../s1/geometry.mjs';
import { parseSvg } from '../s2/svg.mjs';
import { inspectSvg, constructLogo } from '../s2/topology.mjs';
import { rasterMetrics, sha256, renderSizes, portableResult, diagnoseRaster } from '../s3/raster.mjs';

const fail=(code,message,path)=>{const e=new Error(message);e.code=code;e.path=path;throw e};
const obj=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const hex=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x);
const rawHash=x=>sha256(Buffer.isBuffer(x)?x:Buffer.from(typeof x==='string'?x:JSON.stringify(x),'utf8'));
const safeError=e=>({code:e?.code??'UNKNOWN_GEOMETRY_ERROR',field:e?.path??null,message:String(e?.message??'Unknown error').slice(0,400),status:e?.code==='INVALID_SVG'||e?.code==='INVALID_SCHEMA'?'INVALID_INPUT':'UNSUPPORTED'});
const rasterAbsent=()=>[{status:'NOT_EVALUATED',reason:'No raster requested or verified',recognition:'NOT_EVALUATED'}];
const caps=()=>({nativeGeometry:'AVAILABLE',svgSubset:'BOUNDED',raster:'NOT_EVALUATED',dom:'NOT_EVALUATED',browser:'NOT_PROBED',independentReviewer:'NOT_RUN',universalGauntlet:'NOT_REQUIRED'});
const shallow=(x)=>({id:x.id,kind:x.kind});

function observationOfShape(s){const id=s.id,unit='document-unit',observations=[];function obs(property,value,measureUnit='length',provenance='derived-from-declared'){
  observations.push({id:`${id}:${property}`,shapeId:id,property,value,unit:measureUnit==='length'?unit:measureUnit,provenance,sourceField:`shapes[id=${id}].${property}`});
}if(s.kind==='circle'){const kind=renderedCircleClass(s.transform);observations.push({id:`${id}:renderedClass`,shapeId:id,property:'renderedClass',value:kind,unit:'category',provenance:'derived-from-declared',sourceField:`shapes[id=${id}].transform`});if(kind==='circle')obs('radius',s.radius*Math.hypot(s.transform[0],s.transform[1]));}
if(s.kind==='ellipse'){obs('radiusX',s.radiusX);obs('radiusY',s.radiusY)}
if(s.center){const [x,y]=transformPoint(s.center,s.transform);obs('center.x',x);obs('center.y',y)}
if(s.kind==='line'){const a=transformPoint(s.start,s.transform),b=transformPoint(s.end,s.transform);obs('length',Math.hypot(b[0]-a[0],b[1]-a[1]));}
return observations;
}
function suggestedPhi(items){const circles=items.filter(x=>x.kind==='circle'&&Number.isFinite(x.r)&&x.r>0);if(circles.length!==2)return [];const [a,b]=circles,outer=a.r>=b.r?a:b,inner=a.r>=b.r?b:a;const actual=outer.r/inner.r,target=PHI;
return [{id:'inferred:circle-radius-ratio',lhs:`${outer.id}.radius`,rhs:`${inner.id}.radius`,actual,target,relativeResidual:Math.abs(actual/target-1),provenance:'inferred',declaredIntent:'NOT_KNOWN',status:'HYPOTHESIS_ONLY',method:'measured-v1-circle-radii',note:'A numerical fit does not prove designer intent, and cannot satisfy a declared constraint.'}];
}
function finish({type,sourceDigest,measurements=[],constraints=[],topology=null,diagnostics=[],inferred=[],capabilities=caps(),opticalExceptions=[],state,method,artifactId=null}){
 const errors=diagnostics.filter(x=>['FAIL','INVALID_INPUT','UNSUPPORTED'].includes(x.status));const hard=constraints.filter(x=>x.severity==='hard'&&x.status==='FAIL');
 let verdict=state??(errors.some(x=>x.status==='INVALID_INPUT')?'INVALID_INPUT':errors.some(x=>x.status==='UNSUPPORTED')?'UNSUPPORTED':hard.length||topology?.status==='FAIL'||errors.some(x=>x.status==='FAIL')?'NEEDS_WORK':constraints.length===0&&!topology?'REQUIRES_REVIEW':'PASS_TECHNICAL');
 // No vector proof, no browser rendering and no human recognizability PASS is ever inferred.
 return {schema:'geometry-report/1',toolVersion:'s4-portable/1',artifactType:type,artifactId,sourceDigest,method,verdict,measurements,constraints,topology,inferred,diagnostics,capabilities,rasterChecks:rasterAbsent(),opticalExceptions,review:{provenance:'self-service-data-only',humanApproval:'NOT_GIVEN',recognition:'NOT_EVALUATED'},summary:{hardFailureIds:hard.map(x=>x.id),diagnosticsCount:diagnostics.length,visualAcceptance:'NOT_EVALUATED',identityApproval:'NOT_GIVEN'}};
}
export function auditDocument(input){const r=analyze(input),doc=r.document,diagnostics=[],measurements=doc.shapes.flatMap(observationOfShape);const constraints=r.constraints.relations.map(c=>({...c,sourceField:`relationships[id=${c.id}]`,measureUnits:c.kind==='angle'?'radians':c.kind==='ratio'?'unitless':c.lhs.unit}));
 for(const s of doc.shapes)if(s.kind==='circle'&&renderedCircleClass(s.transform)!=='circle')diagnostics.push({status:'FAIL',code:'DECLARED_CIRCLE_RENDERED_ELLIPSE',featureId:s.id,sourceField:`shapes[id=${s.id}].transform`,message:'Affine transform changes rendered circle into ellipse; do not assert circle fidelity.'});
 let topology=null;if(doc.policy?.mode?.startsWith('logo'))try{const result=constructLogo(input);topology=result.topology??null;if(!topology)diagnostics.push({status:result.code==='INFEASIBLE'?'FAIL':'UNSUPPORTED',code:result.code??'TOPOLOGY_NOT_EVALUATED',featureId:doc.id,message:'Logo topology was not constructed; hard constraints failed or topology unsupported'});}catch(e){diagnostics.push({...safeError(e),featureId:doc.id,code:e.code??'TOPOLOGY_UNSUPPORTED'});}
 const circleShapes=doc.shapes.filter(s=>s.kind==='circle'&&renderedCircleClass(s.transform)==='circle').map(s=>({kind:'circle',id:s.id,r:s.radius*Math.hypot(s.transform[0],s.transform[1])}));return finish({type:'geometry-document',artifactId:doc.id,sourceDigest:r.sourceDigest,method:'S1-parametric-measurements-and-optional-S2-topology',measurements,constraints,topology,diagnostics,inferred:doc.relationships.length?[]:suggestedPhi(circleShapes)});
}
export function auditSvg(source,{mode='logo-standard',expectedShapeKinds={},rasterSizes=null,renderer='inkscape'}={}){if(typeof source!=='string'||source.length>100000)fail('INVALID_INPUT','Expected bounded SVG source','input');const sourceDigest=rawHash(source);let parsed,topology,diagnostics=[],measurements=[],inferred=[];try{parsed=parseSvg(source);topology=inspectSvg(source,{mode});for(const s of parsed.items){const id=s.id;let measure={id,featureId:id,kind:s.kind,provenance:'inferred',sourceField:'SVG element / rendered fill (not original design construction)',unit:'svg-viewBox-unit'};if(s.kind==='circle')Object.assign(measure,{center:[s.cx,s.cy],radius:s.r,fill:s.fill});else if(s.kind==='ellipse')Object.assign(measure,{center:[s.cx,s.cy],radiusX:s.rx,radiusY:s.ry,fill:s.fill});else if(s.kind==='rectContours')Object.assign(measure,{contours:s.contours.map(c=>({x0:c.x0,y0:c.y0,x1:c.x1,y1:c.y1})),fill:s.fill});measurements.push(measure);if(s.kind==='ellipse'&&Math.abs(s.rx-s.ry)>1e-9)diagnostics.push({status:expectedShapeKinds[id]==='circle'?'FAIL':'OBSERVATION',code:'ELLIPSE_NOT_CIRCLE',featureId:id,sourceField:'SVG ellipse rx/ry',message:'Ellipse radii differ. Circle provenance cannot be inferred.',actual:[s.rx,s.ry]});}inferred=suggestedPhi(parsed.items)}catch(e){diagnostics.push({...safeError(e),featureId:e.path??'svg',fallback:'Inspect with an SVG-capable viewer; no geometry was guessed'});}const report=finish({type:'svg',sourceDigest,method:'S2-strict-XML-subset-and-topology',measurements,topology,diagnostics,inferred,state:parsed?undefined:'UNSUPPORTED'});
 if(rasterSizes!==null&&parsed){if(!Array.isArray(rasterSizes)||rasterSizes.length<1||rasterSizes.length>12||!rasterSizes.every(x=>Number.isInteger(x)&&x>=1&&x<=2048))fail('INVALID_INPUT','Requested raster sizes must be 1..2048');const rendered=renderSizes(source,{sizes:rasterSizes,binary:renderer});report.capabilities.raster=rendered.status;if(rendered.status==='EXECUTED')report.rasterChecks=portableResult(rendered).results.map(x=>({...x,diagnostic:diagnoseRaster(x.metrics,{expectedComponents:topology.components,expectedHoles:topology.holes}),renderer:rendered.renderer.version,sourceSha256:rendered.sourceSha256,recognition:'NOT_EVALUATED'}));else report.rasterChecks=[{status:'BLOCKED_ENV',reason:'Real renderer not available',renderer:rendered.capability?.reason,recognition:'NOT_EVALUATED'}];if(rendered.status==='EXECUTED'){const states=report.rasterChecks.map(x=>x.diagnostic.status);if(states.includes('FAIL'))report.verdict='NEEDS_WORK';else if(states.some(x=>x==='INDETERMINATE'||x==='NOT_EVALUATED')&&report.verdict==='PASS_TECHNICAL')report.verdict='REQUIRES_REVIEW'}else if(report.verdict==='PASS_TECHNICAL')report.verdict='REQUIRES_REVIEW';}
 return report;
}
export function auditScreenshot(png,{sourceLabel=null}={}){if(!Buffer.isBuffer(png)||png.length>25000000)fail('INVALID_INPUT','Expected bounded PNG buffer');const metrics=rasterMetrics(png);const report=finish({type:'screenshot',sourceDigest:rawHash(png),method:'actual-PNG-bytes-and-pixel-metrics-only',measurements:[{id:'pixel-image',width:metrics.width,height:metrics.height,visualMassProxyCentroid:metrics.visualMassProxyCentroid,unit:'pixel',provenance:'measured-pixels',sourceLabel}],topology:null,diagnostics:[{status:'NOT_EVALUATED',code:'NO_VECTOR_ORIGINAL',message:'PNG cannot prove exact SVG radii, author intent or hidden path topology'}],state:'REQUIRES_REVIEW',capabilities:{...caps(),raster:'ACTUAL_PIXELS_DECODED',svgSubset:'NOT_APPLICABLE'}});report.rasterChecks=[{status:'OBSERVED_PIXELS_ONLY',pngSha256:report.sourceDigest,width:metrics.width,height:metrics.height,thresholds:metrics.thresholds,recognition:'NOT_EVALUATED',originalVectorTopology:'NOT_EVALUATED'}];return report;
}
export function auditDomSnapshot(snapshot){if(snapshot===undefined||snapshot===null)return finish({type:'dom',sourceDigest:null,method:'no-renderer-no-dom-data',state:'NOT_EVALUATED',diagnostics:[{status:'NOT_EVALUATED',code:'MISSING_DOM_CAPTURE',message:'No actual DOM capture attached; do not infer box geometry from HTML/CSS prose.'}],capabilities:{...caps(),dom:'BLOCKED_ENV',browser:'NOT_PROBED'}});
if(!obj(snapshot)||!Array.isArray(snapshot.boxes)||snapshot.boxes.length>3000)fail('INVALID_INPUT','Expected DOM snapshot with <=3000 boxes');const seen=new Set();const boxes=snapshot.boxes.map((b,i)=>{if(!obj(b)||typeof b.id!=='string'||!b.id||b.id.length>100||![b.x,b.y,b.width,b.height].every(v=>typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<=1e7)||b.width<0||b.height<0||seen.has(b.id))fail('INVALID_INPUT',`Invalid or duplicated DOM box ${i}`);seen.add(b.id);return {id:b.id,x:b.x,y:b.y,width:b.width,height:b.height,unit:'css-px',provenance:'provided-external-snapshot',verifiedByAuditor:false}});return finish({type:'dom',sourceDigest:rawHash(snapshot),method:'provided-measured-boxes-no-live-DOM-access',measurements:boxes,state:'REQUIRES_REVIEW',diagnostics:[{status:'NOT_EVALUATED',code:'NO_BROWSER_PROVENANCE',message:'Provided boxes are not an actual browser render verified by this auditor; no hidden vector topology or interaction verification.'}],capabilities:{...caps(),dom:'PROVIDED_SNAPSHOT_UNVERIFIED',browser:'NOT_PROBED'}});
}
export function audit(input,{kind='auto',mode='logo-standard',rasterSizes=null}={}){if(kind==='dom')return auditDomSnapshot(input);if(kind==='screenshot')return auditScreenshot(input);if(kind==='document'||kind==='auto'&&obj(input))return auditDocument(input);if(kind==='svg'||kind==='auto'&&typeof input==='string')return auditSvg(input,{mode,rasterSizes});fail('INVALID_INPUT','Unsupported audit artifact type');}
