#!/usr/bin/env node
// S4: standalone, offline, source-preserving inspect/propose command.
import { readFile, writeFile, stat, link, rm } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { audit, auditDomSnapshot } from './auditor.mjs';
import { proposeRadius } from './proposals.mjs';
const fail=(code,msg)=>{let e=new Error(msg);e.code=code;throw e};
function parse(args){const [command,source,...rest]=args;const flags={};for(let i=0;i<rest.length;i+=2){const key=rest[i]?.slice(2),value=rest[i+1];if(!rest[i]?.startsWith('--')||value===undefined||!['out','report','shape','radius','rule','reason','base-sha','mode','sizes'].includes(key)||Object.hasOwn(flags,key))fail('INVALID_ARGUMENT','Unknown or repeated option');flags[key]=value}return {command,source,flags}}
async function readSource(file){const path=resolve(file);const ext=extname(path);if(!['.json','.svg','.png','.html','.htm','.css'].includes(ext))fail('INVALID_INPUT','Expected .json, .svg, .png, .html, or .css');const st=await stat(path);if(st.size>25000000)fail('LIMIT_EXCEEDED','File exceeds 25MB bound');const bytes=await readFile(path);if(ext==='.png')return {input:bytes,kind:'screenshot'};if(ext==='.html'||ext==='.htm'||ext==='.css')return {input:null,kind:'dom'};if(ext==='.svg')return {input:bytes.toString('utf8'),kind:'svg'};return {input:JSON.parse(bytes.toString('utf8')),kind:'document'}}
async function outputNew(file,content){const path=resolve(file),tmp=path+'.tmp-'+randomBytes(8).toString('hex');try{await stat(path);fail('OUTPUT_EXISTS','Refuse existing output path: '+path)}catch(e){if(e.code!=='ENOENT')throw e}try{await writeFile(tmp,content,{flag:'wx'});await link(tmp,path)}finally{await rm(tmp,{force:true}).catch(()=>{})}}
export async function runCLI(argv){const {command,source,flags}=parse(argv);if(!['audit','propose'].includes(command)||!source)fail('INVALID_ARGUMENT','Use audit FILE or propose FILE with options');const sourcePath=resolve(source),{input,kind}=await readSource(source);let record,candidate=null;if(command==='audit'){
 if(flags.shape||flags.radius||flags.rule||flags.reason||flags['base-sha'])fail('INVALID_ARGUMENT','Proposal flags not permitted for audit');record=kind==='dom'?auditDomSnapshot():kind==='svg'&&flags.sizes?audit(input,{kind,mode:flags.mode??'logo-standard',rasterSizes:flags.sizes.split(',').map(Number)}):audit(input,{kind,mode:flags.mode??'logo-standard'});
 }else{
 if(kind!=='document'||!flags.out)fail('UNSUPPORTED_GEOMETRY','Propose currently accepts native JSON only with explicit --out candidate path');if(flags.mode||flags.sizes)fail('INVALID_ARGUMENT','No view options for native proposal');const result=proposeRadius(input,{expectedSourceDigest:flags['base-sha'],shapeId:flags.shape,newRadius:Number(flags.radius),reason:flags.reason,ruleId:flags.rule});record={schema:'geometry-cli-proposal/1',status:result.status,change:result.change,sourceDigest:result.sourceDigest,candidateDigest:result.candidateDigest,comparison:{verdict:result.comparison.verdict,regressionReasons:result.comparison.regressionReasons},ownerApproval:result.ownerApproval};if(result.status==='REJECTED_REGRESSION')return {code:3,record};candidate=JSON.stringify(result.candidate,null,2)+'\n';
 }
 const outPath=flags.out?resolve(flags.out):null,reportPath=flags.report?resolve(flags.report):null;if([outPath,reportPath].some(x=>x===sourcePath)||outPath&&outPath===reportPath)fail('INVALID_ARGUMENT','Outputs cannot overwrite source or each other');if(command==='audit'&&outPath)fail('INVALID_ARGUMENT','audit accepts --report only');if(candidate!==null)await outputNew(outPath,candidate);if(reportPath)await outputNew(reportPath,JSON.stringify(record,null,2)+'\n');return {code:record.verdict==='NEEDS_WORK'?3:record.verdict==='INVALID_INPUT'?2:record.verdict==='UNSUPPORTED'||record.verdict==='NOT_EVALUATED'||record.verdict==='REQUIRES_REVIEW'?4:0,record};}
const invoked=process.argv[1]&&resolve(process.argv[1])===resolve(fileURLToPath(import.meta.url));if(invoked)runCLI(process.argv.slice(2)).then(r=>{console.log(JSON.stringify(r.record));process.exitCode=r.code}).catch(e=>{console.error(JSON.stringify({code:e.code??'UNEXPECTED_ERROR',message:e.message}));process.exitCode=e.code==='UNSUPPORTED_GEOMETRY'?4:['INVALID_INPUT','INVALID_ARGUMENT','OUTPUT_EXISTS','BASELINE_DIGEST_MISMATCH','INVALID_PROPOSAL'].includes(e.code)?2:5});
