// S5: bounded semantic region tree + distinct deterministic composition grammars.
import { PHI, digest } from '../s1/geometry.mjs';
import { generateTokens } from './tokens.mjs';
export const COMPOSITION_SCHEMA='geometry-composition/1';
export const FAMILIES=['editorial-centered','media-lead','layered-focal'];
const SIZES=[320,390,768,1280,1920];
function fail(code,field,msg){const e=new Error(msg);e.code=code;e.field=field;throw e}
function text(s,field,max=12000){if(typeof s!=='string'||!s.trim()||s.length>max)fail('INVALID_CONTENT',field,'Nonempty bounded string required');return s}
function id(s){if(typeof s!=='string'||!/^[a-z][a-z0-9-]{0,50}$/.test(s))fail('INVALID_ID','id','Invalid id');return s}
function box(x,y,width,height){if(![x,y,width,height].every(v=>Number.isFinite(v)&&Math.abs(v)<1e7)||width<=0||height<=0)fail('INVALID_BOX','layout','Non-positive/invalid bounds');return {x,y,width,height}}
function rng(seed){let n=(seed>>>0)||1;return ()=>{n^=n<<13;n^=n>>>17;n^=n<<5;return (n>>>0)/4294967296}}
function node(id,role,children=[],contentRef=null,meta={}){return {id,role,contentRef,children,...meta}}
function semanticTree(family,cardCount){const title=node('title','heading',[],'title'),intro=node('intro','paragraph',[],'intro'),action=node('action','action',[],'cta'),media=node('media','figure',[],'media'),quote=node('quote','blockquote',[],'quote'),cards=node('collection','collection',Array.from({length:cardCount},(_,i)=>node('card-'+(i+1),'article',[],'cards.'+i)));
 if(family==='editorial-centered')return node('page','page',[node('headline','header',[title,intro,action]),node('feature','feature',[media,quote]),cards]);
 if(family==='media-lead')return node('page','page',[node('hero','hero',[node('visual','visual',[media]),node('story','story',[title,intro,action])]),node('support','support',[quote,cards])]);
 return node('page','page',[node('focal-stage','focal-stage',[node('narrative','narrative',[title,intro,action,quote]),node('backdrop','backdrop',[media])]),cards]);}
function countNodes(n){return 1+n.children.reduce((s,x)=>s+countNodes(x),0)}
function regionsFor(family,width,cardCount,gap,offset){const narrow=width<760,contentWidth=Math.min(1240,width-2*(width<600?16:width<1100?32:48));const x=(width-contentWidth)/2;
 const heroTop=24,heroHeight=narrow?560:family==='layered-focal'?500:430,mediaFraction=1/PHI;
 const main=box(x,heroTop,contentWidth,heroHeight);let copy,media,ratio=null,exceptions=[];
 if(narrow){copy=box(x,heroTop,contentWidth,255);media=box(x,heroTop+280,contentWidth,260);exceptions.push({id:'narrow-reflow',source:'phi-as-soft-rule',reason:'text/action visibility and reading order',viewport:width,status:'OVERRIDE'});}
 else if(family==='editorial-centered'){copy=box(x+contentWidth*.08,heroTop,contentWidth*.84,175);media=box(x,heroTop+205,contentWidth/PHI,225);ratio={rule:'phi-child-width',lhs:'media.width',rhs:'feature.remaining',target:PHI,actual:(media.width/(contentWidth-media.width)),residual:Math.abs(media.width/(contentWidth-media.width)-PHI),unit:'CSS px',provenance:'declared'};}
 else if(family==='media-lead'){const usable=contentWidth-gap,desired=usable*mediaFraction;media=box(x,heroTop,desired,390);copy=box(x+desired+gap,heroTop,usable-desired,390);ratio={rule:'phi-split',lhs:'media.width',rhs:'copy.width',target:PHI,actual:media.width/copy.width,residual:Math.abs(media.width/copy.width-PHI),unit:'CSS px',provenance:'declared'};}
 else {copy=box(x+20,heroTop+40,contentWidth*.55,310);media=box(x+contentWidth*.58,heroTop+150,contentWidth*.42,290);ratio={rule:'diagonal-canon',lhs:'media.anchor',rhs:'stage.diagonal',target:null,actual:null,residual:null,unit:'CSS px',provenance:'declared',note:'not golden angle; focal stage uses diagonal positioning'};}
 const gridTop=heroTop+heroHeight+(narrow?36:65);const cols=width<600?1:width<1050?2:3;const cardWidth=(contentWidth-gap*(cols-1))/cols;const cardHeight=170+offset;const cards=Array.from({length:cardCount},(_,i)=>box(x+(i%cols)*(cardWidth+gap),gridTop+Math.floor(i/cols)*(cardHeight+gap),cardWidth,cardHeight));return {viewport:width,mode:narrow?'stacked':'desktop',frame:box(x,0,contentWidth,gridTop+Math.ceil(cardCount/cols)*(cardHeight+gap)),copy,media,cards,quote:family==='editorial-centered'?box(x+contentWidth*.66,heroTop+205,contentWidth*.34,225):family==='media-lead'?box(x,gridTop-50,contentWidth,40):box(x+20,heroTop+375,contentWidth*.55,75),rule:ratio,exceptions,gridColumns:cols,negativeSpace:{horizontalMargin:x,cardGap:gap,nonCoveredAreaLowerBoundEstimate:Math.max(0,contentWidth*heroHeight-copy.width*copy.height-media.width*media.height),accuracy:'coarse-estimate-overlap-not-subtracted'}}}
export function generateCompositions(input){if(!input||typeof input!=='object'||Array.isArray(input)||input.schema!==COMPOSITION_SCHEMA)fail('INVALID_SCHEMA','schema',COMPOSITION_SCHEMA);id(input.id);const c=input.content;if(!c||typeof c!=='object')fail('INVALID_CONTENT','content','Content object required');const content={title:text(c.title,'title',300),intro:text(c.intro,'intro'),cta:text(c.cta,'cta',500),mediaLabel:text(c.mediaLabel??'Synthetic media image','mediaLabel',200),quote:text(c.quote??'Synthetic editorial quotation','quote'),cards:c.cards??[]};if(!Array.isArray(content.cards)||content.cards.length>36)fail('INVALID_CONTENT','cards','0..36 array');content.cards=content.cards.map((v,i)=>({title:text(v.title,'cards.'+i+'.title',500),body:text(v.body,'cards.'+i+'.body')}));const seed=input.seed??1;if(!Number.isInteger(seed)||seed<0||seed>4294967295)fail('INVALID_SEED','seed','unsigned 32-bit seed');const rand=rng(seed),gapToken=generateTokens().manifest.primitives.find(t=>t.id==='gap-card'),gap=gapToken.actualPx,offset=Math.floor(rand()*7);const families=input.referenceFamily?[input.referenceFamily]:FAMILIES;if(families.some(f=>!FAMILIES.includes(f)))fail('INVALID_FAMILY','referenceFamily','Unknown fixed layout');const sizes=input.viewports??SIZES;if(!Array.isArray(sizes)||!sizes.length||sizes.length>10||sizes.some(v=>!Number.isInteger(v)||v<280||v>4096))fail('INVALID_VIEWPORT','viewports','280..4096 integer CSS pixels');
 const candidates=families.map((family,i)=>{const tree=semanticTree(family,content.cards.length);const layouts=sizes.map(width=>regionsFor(family,width,content.cards.length,gap,offset+i));const grammar=[{type:'split',scope:'feature',family:family==='layered-focal'?'diagonal-canon':'phi-power',provenance:'declared'}, {type:'focal',scope:'media',anchor:'declared-media-frame-center',provenance:'layout-author-intent-not-image-saliency'}, {type:'safeZone',scope:'copy',minimum:'content-and-action-visible'}, {type:'rhythm',scope:'collection',sharedToken:'gap-card'}];const readingOrder=['title','intro','action','media','quote',...content.cards.map((_,k)=>'card-'+(k+1))];return {id:input.id+'-'+family,family,seed,tree,treeNodeCount:countNodes(tree),grammar,readingOrder,layouts,styleHints:{desktop:family==='editorial-centered'?'grid-area story spanning; figure and quote split':family==='media-lead'?'CSS Grid media left, narrative right':'CSS Grid layered focal stage with aligned content',mobile:'flex column, narrative before media; cards reflow',source:'generated-preview.mjs'},rasterState:'NOT_EVALUATED',semanticProof:'provided content metadata only',digest:digest({family,tree,layouts,seed,content})}});
 return {schema:'geometry-compositions/1',inputDigest:digest(input),source:'declared-brief',candidates,cardGapContract:{sourceToken:'gap-card',cssAlias:'--geo-card-gap',cssValue:gapToken.cssValue,unit:gapToken.unit,referenceRootFontPx:16,referencePx:gap,expectedPxAt32Root:gapToken.unit==='rem'?Number((gap*2).toFixed(6)):gap,actualDom:'NOT_EVALUATED',scope:'reference-root-proposed-regions-not-live-browser'},claim:{visualQuality:'NOT_EVALUATED',browserRendered:'NOT_EVALUATED'},distinctStructures:new Set(candidates.map(x=>JSON.stringify(x.tree))).size===candidates.length};}
